### ISSUE TITLE
need help -> https://github.com/TimDaub/simple-caldav

### ISSUE THREAD

**Issue by strukturart** [strukturart/greg#11]
I need help to make this library usable for KaiOs. I packed it with parcelsJS and integrated it with the script tag. but how do i address simple-caldav and start the events?

https://github.com/TimDaub/simple-caldav

**Comment by arma7x** [comment]
Maybe you can try this library https://github.com/natelindev/tsdav

**Comment by strukturart** [comment]
@arma7x have you used tsdav before?

**Comment by arma7x** [comment]
> @arma7x have you used tsdav before?

No. But https://github.com/natelindev/tsdav#apple-carddav-1 support Basic authentication

**Comment by strukturart** [comment]
Unfortunately, importing and transpiling (parcelJS) the library causes problems in kaiOs
`import { DAVClient } from 'tsdav';`

**Comment by arma7x** [comment]
https://github.com/strukturart/greg/pull/18

Please exclude folder **.cache** and **build**

**Comment by arma7x** [comment]
noted: https://github.com/parcel-bundler/parcel/issues/2833#issuecomment-509680519

**Comment by strukturart** [comment]
sorry for the chaos, but this is currently the latest branch: https://github.com/strukturart/greg/tree/mithdril

**Comment by arma7x** [comment]
@strukturart why not dev in master and use branching for release ?

**Comment by strukturart** [comment]
> noted: [parcel-bundler/parcel#2833 (comment)](https://github.com/parcel-bundler/parcel/issues/2833#issuecomment-509680519)

I have to use type="module" otherwise I can't use import / export

**Comment by arma7x** [comment]
> > noted: [parcel-bundler/parcel#2833 (comment)](https://github.com/parcel-bundler/parcel/issues/2833#issuecomment-509680519)
> 
> I have to use type="module" otherwise I can't use import / export

I'm not having those issues and this is my build script https://github.com/arma7x/greg/blob/master/package.json#L7-L10

**Comment by strukturart** [comment]
i think the problem with type=module is not current in the latest parcel version. which version do you use?
this is my build script: https://github.com/strukturart/greg/blob/mithdril/build.sh

**Comment by arma7x** [comment]
> i think the problem with type=module is not current in the latest parcel version. which version do you use? this is my build script: https://github.com/strukturart/greg/blob/mithdril/build.sh

1.12.5. I will upgrade to v2 and then debug this issues

**Comment by arma7x** [comment]
Upgraded to Parcelv2, **yarn start** & **yarn build** does not reproduce any errors

https://github.com/arma7x/greg/commit/60c70c4ce5bdd2865c489245f2838c0fa6f202ee

**Comment by arma7x** [comment]
this is [.babelrc](https://github.com/arma7x/greg/commit/572ebcd17f1d99c0d2e1ea21213d71ec6eabab5c) configuration to support async/await for KaiOS device. But i'm not sure why my script does not copy `application/manifest.webapp` into folder `dist`

**Comment by strukturart** [comment]
@arma7x Basically, tsdav works now, but it's not entirely clear to me where I should enter the access data from a nextcloud account. the documentation is not very helpful or requires a lot of prior knowledge.

**Comment by arma7x** [comment]
This is the list of supported cloud provider https://tsdav.vercel.app/docs/intro. I will signup a NextCloud account for testing.

Instead of install the library from npm, maybe you should load the library via script tag since KaiOS XMLHttpRequest support cors, https://github.com/natelindev/tsdav/blob/master/dist/tsdav.js#L519

**Comment by arma7x** [comment]
> tsdav works now

You can connect to NextCloud server ?

**Comment by arma7x** [comment]
@strukturart I can connect to my nextcloud account

**Comment by strukturart** [comment]
> @strukturart I can connect to my nextcloud account

can you please show me the snippet how to log in with tsdav.

this is my attempt: https://github.com/strukturart/greg/blob/d4f8329876d7a11576860f13336d4afa79ed10b9/application/app.js#L21

**Comment by arma7x** [comment]
1. This is the configuration https://github.com/arma7x/greg/blob/master/application/app.js#L1867-L1887
2. I modified the DAV client https://github.com/arma7x/greg/blob/master/application/assets/js/tsdav.js
3. Greg can connect(authenticate & fetch resources) to DAV server but the client unable to parse the response(KaiOS can't compile RegExp expression)

**Comment by arma7x** [comment]
@strukturart i send the password to your email(email address on github profile)

**Comment by strukturart** [comment]
thanks now it works with the login. I switched to type: caldav.
https://github.com/strukturart/greg/blob/dafb3f5d4325458a4fa64a0efa8ff6e62e63617c/application/app.js#L21

**Comment by arma7x** [comment]
Successfully connect and fetch calendars & events, this is latest update https://github.com/arma7x/greg/commit/f8fd4dd49ccb86dc6eec6ea235f4144dddf95189

Required `@babel/plugin-transform-named-capturing-groups-regex` as devdependecies and import the plugin in `.babelrc`

**Comment by strukturart** [comment]
Thank you very much, now it works for me too with loading the calendar data.
