### ISSUE TITLE
`master` won't build, missing `google_cred.js`

### ISSUE THREAD

**Issue by ghost** [strukturart/greg#28]
Hello there, just tried to build this from `master` and it seems that `google_cred.js` is missing: https://github.com/strukturart/greg/blob/master/application/app.js#L24

Looks like this is meant to be used with a Google OAuth Application credential; is it possible to set a build flag that could mock this / avoid its use if Google isn't being used?

**Comment by strukturart** [comment]
Hello @invariant ,

you must use your own google cred, the content of the file must have the following structure:

```
export const google_cred = {
  clientId:
    "xxx",
  clientSecret: "xxxx",
};

```
