### ISSUE TITLE
Notifications not firing

### ISSUE THREAD

**Issue by NuclearKev** [strukturart/greg#3]
Device: Go Flip 4
OS: KaiOS 3.0
Version: `master`

When I set an event to give me a notification _x_ minutes before the event it never fires. Could be KaiOS 3.0 specific. 

PS: an options to fire a notification at the start of an event would be nice too ;)

**Comment by strukturart** [comment]
pls try the new version

**Comment by NuclearKev** [comment]
It appears to still not work with `master`.

**Comment by NuclearKev** [comment]
I don't see a notification permission in the settings either.

**Comment by strukturart** [comment]
@NuclearKev do you have a way to see the console.log output of the app?

**Comment by NuclearKev** [comment]
> @NuclearKev do you have a way to see the console.log output of the app?

I know that I can't using Firefox/Nightly to view the log but I haven't tried logcat - I can try it sometime (probably not this week, however).

**Comment by NuclearKev** [comment]
I was able to get logcat running via adb. Here is the output from me opening `greg`: 
```
12-30 21:00:10.875  1704  1704 E /system/b2g/b2g: Failed to get IAshmemDeviceService.
12-30 21:00:17.766   695   975 W api_daemon::session: Processing 'ProcManagerService request: ProcessServiceCommit' took too long: 12ms
12-30 21:00:17.967   693  4008 E Sandbox : SandboxBroker: denied op=open rflags=2400000 perms=0 path=/data/misc/zoneinfo/current/tzdata for pid=4006
12-30 21:00:17.971   693  4008 E Sandbox : SandboxBroker: denied op=open rflags=2400000 perms=0 path=/data/misc/zoneinfo/current/tzdata for pid=4006
12-30 21:00:18.291   695   975 W api_daemon::session: Processing 'ProcManagerService request: ProcessServiceCommit' took too long: 11ms
12-30 21:00:18.382   693  4008 E Sandbox : SandboxBroker: denied op=open rflags=2500000 perms=0 path=/dev/__properties__/u:object_r:use_memfd_prop:s0 for pid=4006
12-30 21:00:18.382  4006  4006 E libc    : Access denied finding property "sys.use_memfd"
12-30 21:00:18.388   693  4008 E Sandbox : SandboxBroker: denied op=access rflags=6 perms=0 path=/dev/binder for pid=4006
12-30 21:00:18.388  4006  4006 E /system/b2g/b2g: Failed to get IAshmemDeviceService.
12-30 21:00:18.522  4006  4006 E /system/b2g/b2g: Failed to get IAshmemDeviceService.
12-30 21:00:18.566   693   693 E GeckoConsole: [JavaScript Error: "uncaught exception: Object"]
12-30 21:00:22.703   387   387 E cutils-trace: Error opening trace file: No such file or directory (2)
12-30 21:00:22.918   387   387 W Gralloc3: mapper 3.x is not supported
```

It doesn't appear that any useful information was logged in regards to this issue.

**Comment by strukturart** [comment]
thanks, I think these are system outputswould it be possible to show me the console.log output of the webIDE?

I would be interested in this https://github.com/strukturart/greg/blob/32dc7193f79870c13e18a6bf7c746cd4e7cf1efd/application/index.js#L2

**Comment by NuclearKev** [comment]
As of now, I cannot connect the GF4 to the webide. It requires root permissions.

**Comment by strukturart** [comment]
okay, i can also write the information in an alert ().

**Comment by NuclearKev** [comment]
I updated to the latest commit on master and I don't get any alert.

**Comment by strukturart** [comment]
@NuclearKev do you still use my app and want to help me solve the alarm api bug like this?
