### ISSUE TITLE
Display content of the event in the notification

### ISSUE THREAD

**Issue by bmndc** [strukturart/greg#33]
Device: Nokia 6300 4G
OS: KaiOS 2.5.4
Version: `master`

Right now, event alerts only display 'Greg' in the title and not much else. This might be problematic to events that happen at the same time.

I suggest having the name of the event as the notification title, and the time of the event in the description e.g.

```
Buy diamond ring
15:00 - 15:30
```

```
Dinner with perry
20:00 - 21:00
```

**Comment by strukturart** [comment]
please test the latest app version

**Comment by strukturart** [comment]
@minhduc-bui1 Tested ?
