### ISSUE TITLE
Deleting Events

### ISSUE THREAD

**Issue by Racing-Dog** [strukturart/greg#36]
Being a mere mortal and therefore imperfect, I make mistakes. And sometimes valid things simply become un-needed. So if that relates to a future Event, how do I delete that Event? I couldn't spot anything in the Help, but that could just mean I need to go to SpecSavers.

If it can't be done at the moment, can it be added please?

**Comment by strukturart** [comment]
you can delete events when you edit the event. In the calendar view, press 5 to open and edit an event. In the next version of the app you will be able to delete an event more directly.

**Comment by Racing-Dog** [comment]
Thanks for that.
