### ISSUE TITLE
Events appear on wrong day

### ISSUE THREAD

**Issue by rmosolgo** [strukturart/greg#43]
Hi! As mentioned before, I'm new to KaiOS and to greg, and I've really appreciated it over the native calendar app. Thanks! 

I noticed that events sometimes appear on the wrong day. Here's an example: 

![Photo on 3-27-24 at 4 23 PM](https://github.com/strukturart/greg/assets/2231765/1c39da1d-04dc-4d8e-b3a5-ab6cf025cb60)

Above, it shows "AidData Summer 2011 Lunch" coming up tomorrow, March 28. In fact, there _were_ events like that in the long past: 

![image](https://github.com/strukturart/greg/assets/2231765/3f23cf9a-1c63-4758-91fe-bd16706a3685)

But, not tomorrow: 

![image](https://github.com/strukturart/greg/assets/2231765/a30e82f2-136f-4575-b936-56adf7988c65)

Do you have a guess why this might be happening? I'd be happy to try fixing it but I'd probably have better luck if you have any clues to share 😅

**Comment by rmosolgo** [comment]
Update: maybe it has to do with how recurring events are rendered. I tried navigating back to 2011 to see if it appeared in the correct place, and while I was on my way there, I noticed that this event is also displayed on Thursdays in 2013: 

![Photo on 3-27-24 at 4 32 PM](https://github.com/strukturart/greg/assets/2231765/772a2b2c-c109-43e6-a1f1-c65b4dacd052)


For reference, here's the configuration of this event in Google: 

![image](https://github.com/strukturart/greg/assets/2231765/a2d47303-d5cb-4fb7-9373-b9652377cd99)


Maybe the "5 times" part isn't applying?

**Comment by strukturart** [comment]
This is where the “cells” are styled:
https://github.com/strukturart/greg/blob/aaca714763b333ba392572a42f979adca01c7e25/application/app.js#L1200

and here the events are parsed:
https://github.com/strukturart/greg/blob/aaca714763b333ba392572a42f979adca01c7e25/application/sw.js#L59

**Comment by strukturart** [comment]
Apparently the number of repetitions is ignored, could you please test whether the problem is solved by specifying an end date?
