### ISSUE TITLE
Can't see the username text field when adding a Google account

### ISSUE THREAD

**Issue by MagicFab** [strukturart/greg#44]
On a Nokia 2780 flip phone, using KAIOS 3.1, the resolution is 320 x 240 (QVGA).

In Accounts > Sign in with Google, the username field name is partially hidden by a black bar with button labels "ENTER.... Done".

During text entry, the bar changes according to autofill settings. This makes it very difficult to enter a username.

![2024-07-04-15-40-54](https://github.com/strukturart/greg/assets/317514/1868bbe1-89b2-4a55-9f78-3d9adfaeca62)

See screenshot.

**Comment by strukturart** [comment]
I can not change this page because it is managed by google.

**Comment by MagicFab** [comment]
As a workaround, if you press "Done" (using the top-right key on the phone), the black bar disappears and a cursor appears. The page can then be scrolled down to make the field completely visible and enter the information.

Is there a way to zoom out that view when such low resolution is detected ?

**Comment by strukturart** [comment]
if you have logged in to google via the browser independently of greg, the login process is easier because you only have to confirm. as far as I know you can zoom in the browser app.
