### ISSUE TITLE
Small typo "Events filterdy" in Key assignment options screen

### ISSUE THREAD

**Issue by MagicFab** [strukturart/greg#45]
When going to the options screen a list of key assignments is shown.

For "0", it indicates "Events filterdy by category", it should be "Events filtered by category".

Apologies for not submitting a pull request directly, it seems I'd need different permissions here.

![2024-07-05-14-47-09](https://github.com/strukturart/greg/assets/317514/8e4f74d1-411a-4be8-b7b5-a6abcd6f212c)

**Comment by strukturart** [comment]
thanks!
