### ISSUE TITLE
After editting an event, going back, and then attempting to view event list you get sent back 1 month

### ISSUE THREAD

**Issue by NuclearKev** [strukturart/greg#7]
Not really sure how to totally explain this but if you do the following it'll happen:
1.) Make an event for today.
2.) Go to today and edit that event.
3.) Leave the event by back button or by saving
4.) Press 'ok' to view list of events again. 
  - The event will not be highlighted
  - The event cannot be highlighted again
  - If you press 'ok' again to return to the calendar, you'll see you're 1 month in the past.

**Comment by strukturart** [comment]
pls try again

**Comment by NuclearKev** [comment]
Fixed. (although a little slow to select the current event but no big deal)
